version: '3'

services:

  django_app:
    build:
      context: ./django_chatbot
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    container_name: chat_application
    volumes:
      - ./django_chatbot:/app
    depends_on:
      - db

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - "5050:80"
    environment:
      - "PGADMIN_DEFAULT_EMAIL=user@domain.com"
      - "PGADMIN_DEFAULT_PASSWORD=SuperSecret"
    depends_on:
      - db

volumes:
  postgres_data: